/* 
 * MELI Markeplace SDK
 *
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 0.0.27
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MeliLibTools.MeliLibApi;
using MeliLibTools.Model;
using MeliLibTools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MeliLibTools.Test
{
    /// <summary>
    ///  Class for testing AttributesValueStruct
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AttributesValueStructTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AttributesValueStruct
        //private AttributesValueStruct instance;

        public AttributesValueStructTests()
        {
            // TODO uncomment below to create an instance of AttributesValueStruct
            //instance = new AttributesValueStruct();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AttributesValueStruct
        /// </summary>
        [Fact]
        public void AttributesValueStructInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AttributesValueStruct
            //Assert.IsInstanceOfType<AttributesValueStruct> (instance, "variable 'instance' is a AttributesValueStruct");
        }


        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Fact]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }

    }

}
