/* 
 * MELI Markeplace SDK
 *
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 0.0.27
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MeliLibTools.MeliLibApi;
using MeliLibTools.Model;
using MeliLibTools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MeliLibTools.Test
{
    /// <summary>
    ///  Class for testing AttributesValues
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AttributesValuesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AttributesValues
        //private AttributesValues instance;

        public AttributesValuesTests()
        {
            // TODO uncomment below to create an instance of AttributesValues
            //instance = new AttributesValues();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AttributesValues
        /// </summary>
        [Fact]
        public void AttributesValuesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AttributesValues
            //Assert.IsInstanceOfType<AttributesValues> (instance, "variable 'instance' is a AttributesValues");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Struct'
        /// </summary>
        [Fact]
        public void StructTest()
        {
            // TODO unit test for the property 'Struct'
        }

    }

}
