/* 
 * MELI Markeplace SDK
 *
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MeliLibTools.MeliLibApi;
using MeliLibTools.Model;
using MeliLibTools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MeliLibTools.Test
{
    /// <summary>
    ///  Class for testing InlineObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineObject
        //private InlineObject instance;

        public InlineObjectTests()
        {
            // TODO uncomment below to create an instance of InlineObject
            //instance = new InlineObject();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineObject
        /// </summary>
        [Fact]
        public void InlineObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineObject
            //Assert.IsInstanceOfType<InlineObject> (instance, "variable 'instance' is a InlineObject");
        }


        /// <summary>
        /// Test the property 'GrantType'
        /// </summary>
        [Fact]
        public void GrantTypeTest()
        {
            // TODO unit test for the property 'GrantType'
        }
        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'ClientSecret'
        /// </summary>
        [Fact]
        public void ClientSecretTest()
        {
            // TODO unit test for the property 'ClientSecret'
        }
        /// <summary>
        /// Test the property 'RedirectUri'
        /// </summary>
        [Fact]
        public void RedirectUriTest()
        {
            // TODO unit test for the property 'RedirectUri'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'RefreshToken'
        /// </summary>
        [Fact]
        public void RefreshTokenTest()
        {
            // TODO unit test for the property 'RefreshToken'
        }

    }

}
