/* 
 * MELI Markeplace SDK
 *
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 0.0.27
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MeliLibTools.MeliLibApi;
using MeliLibTools.Model;
using MeliLibTools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MeliLibTools.Test
{
    /// <summary>
    ///  Class for testing Item
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Item
        //private Item instance;

        public ItemTests()
        {
            // TODO uncomment below to create an instance of Item
            //instance = new Item();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Item
        /// </summary>
        [Fact]
        public void ItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Item
            //Assert.IsInstanceOfType<Item> (instance, "variable 'instance' is a Item");
        }


        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'CategoryId'
        /// </summary>
        [Fact]
        public void CategoryIdTest()
        {
            // TODO unit test for the property 'CategoryId'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'CurrencyId'
        /// </summary>
        [Fact]
        public void CurrencyIdTest()
        {
            // TODO unit test for the property 'CurrencyId'
        }
        /// <summary>
        /// Test the property 'AvailableQuantity'
        /// </summary>
        [Fact]
        public void AvailableQuantityTest()
        {
            // TODO unit test for the property 'AvailableQuantity'
        }
        /// <summary>
        /// Test the property 'BuyingMode'
        /// </summary>
        [Fact]
        public void BuyingModeTest()
        {
            // TODO unit test for the property 'BuyingMode'
        }
        /// <summary>
        /// Test the property 'ListingTypeId'
        /// </summary>
        [Fact]
        public void ListingTypeIdTest()
        {
            // TODO unit test for the property 'ListingTypeId'
        }
        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Fact]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'VideoId'
        /// </summary>
        [Fact]
        public void VideoIdTest()
        {
            // TODO unit test for the property 'VideoId'
        }
        /// <summary>
        /// Test the property 'Warranty'
        /// </summary>
        [Fact]
        public void WarrantyTest()
        {
            // TODO unit test for the property 'Warranty'
        }
        /// <summary>
        /// Test the property 'Pictures'
        /// </summary>
        [Fact]
        public void PicturesTest()
        {
            // TODO unit test for the property 'Pictures'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'Variations'
        /// </summary>
        [Fact]
        public void VariationsTest()
        {
            // TODO unit test for the property 'Variations'
        }

    }

}
