/* 
 * MELI Markeplace SDK
 *
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 0.0.27
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MeliLibTools.MeliLibApi;
using MeliLibTools.Model;
using MeliLibTools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MeliLibTools.Test
{
    /// <summary>
    ///  Class for testing ItemPictures
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ItemPicturesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ItemPictures
        //private ItemPictures instance;

        public ItemPicturesTests()
        {
            // TODO uncomment below to create an instance of ItemPictures
            //instance = new ItemPictures();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ItemPictures
        /// </summary>
        [Fact]
        public void ItemPicturesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ItemPictures
            //Assert.IsInstanceOfType<ItemPictures> (instance, "variable 'instance' is a ItemPictures");
        }


        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

    }

}
