/* 
 * MELI Markeplace SDK
 *
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 0.0.27
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MeliLibTools.MeliLibApi;
using MeliLibTools.Model;
using MeliLibTools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MeliLibTools.Test
{
    /// <summary>
    ///  Class for testing VariationsAttributeCombinations
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VariationsAttributeCombinationsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VariationsAttributeCombinations
        //private VariationsAttributeCombinations instance;

        public VariationsAttributeCombinationsTests()
        {
            // TODO uncomment below to create an instance of VariationsAttributeCombinations
            //instance = new VariationsAttributeCombinations();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VariationsAttributeCombinations
        /// </summary>
        [Fact]
        public void VariationsAttributeCombinationsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VariationsAttributeCombinations
            //Assert.IsInstanceOfType<VariationsAttributeCombinations> (instance, "variable 'instance' is a VariationsAttributeCombinations");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ValueId'
        /// </summary>
        [Fact]
        public void ValueIdTest()
        {
            // TODO unit test for the property 'ValueId'
        }
        /// <summary>
        /// Test the property 'ValueName'
        /// </summary>
        [Fact]
        public void ValueNameTest()
        {
            // TODO unit test for the property 'ValueName'
        }

    }

}
