/* 
 * MELI Markeplace SDK
 *
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 0.0.27
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using MeliLibTools.Client;
using MeliLibTools.MeliLibApi;

namespace MeliLibTools.Test
{
    /// <summary>
    ///  Class for testing CategoriesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CategoriesApiTests : IDisposable
    {
        private CategoriesApi instance;

        public CategoriesApiTests()
        {
            instance = new CategoriesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CategoriesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CategoriesApi
            //Assert.IsType(typeof(CategoriesApi), instance, "instance is a CategoriesApi");
        }

        
        /// <summary>
        /// Test CategoriesCategoryIdGet
        /// </summary>
        [Fact]
        public void CategoriesCategoryIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string categoryId = null;
            //instance.CategoriesCategoryIdGet(categoryId);
            
        }
        
        /// <summary>
        /// Test SitesSiteIdCategoriesGet
        /// </summary>
        [Fact]
        public void SitesSiteIdCategoriesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string siteId = null;
            //instance.SitesSiteIdCategoriesGet(siteId);
            
        }
        
        /// <summary>
        /// Test SitesSiteIdDomainDiscoverySearchGet
        /// </summary>
        [Fact]
        public void SitesSiteIdDomainDiscoverySearchGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string siteId = null;
            //string q = null;
            //string limit = null;
            //instance.SitesSiteIdDomainDiscoverySearchGet(siteId, q, limit);
            
        }
        
    }

}
