/* 
 * MELI Markeplace SDK
 *
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 0.0.27
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using MeliLibTools.Client;
using MeliLibTools.MeliLibApi;
using MeliLibTools.Model;

namespace MeliLibTools.Test
{
    /// <summary>
    ///  Class for testing ItemsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ItemsApiTests : IDisposable
    {
        private ItemsApi instance;

        public ItemsApiTests()
        {
            instance = new ItemsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ItemsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ItemsApi
            //Assert.IsType(typeof(ItemsApi), instance, "instance is a ItemsApi");
        }

        
        /// <summary>
        /// Test ItemsIdGet
        /// </summary>
        [Fact]
        public void ItemsIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.ItemsIdGet(id);
            
        }
        
        /// <summary>
        /// Test ItemsIdPut
        /// </summary>
        [Fact]
        public void ItemsIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string accessToken = null;
            //Item item = null;
            //instance.ItemsIdPut(id, accessToken, item);
            
        }
        
        /// <summary>
        /// Test ItemsPost
        /// </summary>
        [Fact]
        public void ItemsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accessToken = null;
            //Item item = null;
            //instance.ItemsPost(accessToken, item);
            
        }
        
    }

}
