/* 
 * MELI Markeplace SDK
 *
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using MeliLibTools.Client;
using MeliLibTools.MeliLibApi;

namespace MeliLibTools.Test
{
    /// <summary>
    ///  Class for testing RestClientApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RestClientApiTests : IDisposable
    {
        private RestClientApi instance;

        public RestClientApiTests()
        {
            instance = new RestClientApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RestClientApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RestClientApi
            //Assert.IsType(typeof(RestClientApi), instance, "instance is a RestClientApi");
        }

        
        /// <summary>
        /// Test ResourceGet
        /// </summary>
        [Fact]
        public void ResourceGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string resource = null;
            //string accessToken = null;
            //instance.ResourceGet(resource, accessToken);
            
        }
        
        /// <summary>
        /// Test ResourcePost
        /// </summary>
        [Fact]
        public void ResourcePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string resource = null;
            //string accessToken = null;
            //Object body = null;
            //instance.ResourcePost(resource, accessToken, body);
            
        }
        
        /// <summary>
        /// Test ResourcePut
        /// </summary>
        [Fact]
        public void ResourcePutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string resource = null;
            //string accessToken = null;
            //Object body = null;
            //instance.ResourcePut(resource, accessToken, body);
            
        }
        
    }

}
