/* 
 * MELI Markeplace SDK
 *
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 0.0.11
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing NewEndpointsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class NewEndpointsApiTests : IDisposable
    {
        private NewEndpointsApi instance;

        public NewEndpointsApiTests()
        {
            instance = new NewEndpointsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewEndpointsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' NewEndpointsApi
            //Assert.IsType(typeof(NewEndpointsApi), instance, "instance is a NewEndpointsApi");
        }

        
        /// <summary>
        /// Test ItemsIdCatalogForewarningDateGet
        /// </summary>
        [Fact]
        public void ItemsIdCatalogForewarningDateGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string version = null;
            //instance.ItemsIdCatalogForewarningDateGet(id, version);
            
        }
        
        /// <summary>
        /// Test ItemsIdHealthActionGet
        /// </summary>
        [Fact]
        public void ItemsIdHealthActionGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.ItemsIdHealthActionGet(id);
            
        }
        
        /// <summary>
        /// Test ItemsIdHealthGet
        /// </summary>
        [Fact]
        public void ItemsIdHealthGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.ItemsIdHealthGet(id);
            
        }
        
        /// <summary>
        /// Test SitesSiteIdHealthLevelsGet
        /// </summary>
        [Fact]
        public void SitesSiteIdHealthLevelsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string siteId = null;
            //instance.SitesSiteIdHealthLevelsGet(siteId);
            
        }
        
    }

}
